### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by knifecake** [Lletfrix/apuntes#8]
Sobre la revisión del 25 de marzo de 2019 a las 23:12.

* En vez de poner subíndices a las flechas de límites (`\to`), utilizar `\xrightarrow{superíndice}` o, alternativamente, `\xrightarrow[subíndice]{superíndice}` (el primer argumento entre `[]` es opcional.
* P52. Última ecuación. Falta un igual. Debería ser `U(t) = \int_{t_0}^t ...`
* Hay discrepancia entre el ejemplo 33 (P52) y la observación de la página 54. Debería obtenerse la solución asociada a un autovalor de multiplicidad dos dividiendo por 2! o sin dividir (yo apuesto por que no según https://www.math24.net/topics-differential-equations/
* P44. La manera de referirse a la EDO homogénea asociada tiene letras raras. Está bien?

**Comment by lletfrix** [comment]
Entre el ejemplo 33 y la observación de la página 54 dijo Antonio que eran equivalentes, pero que dividir por los factoriales simplificaba los cálculos.

Se usan letras caligráficas indicando que es el nombre de un problema de PVI
